### ISSUE TITLE
Upload NewsreaderDutch Docker image to Dockerhub

### ISSUE THREAD

**Issue by MartineDeVos** [ADAH-EviDENce/NewsReader#24]

**Comment by MartineDeVos** [comment]
Can only be done after the docker builds and runs succesfully on our own systems locally. Nex step is to add run instructions for the image to usage in readme (see issue 26)

**Comment by wmkouw** [comment]
Done. It's in: https://hub.docker.com/r/evidence/newsreaderdutch/
