### ISSUE TITLE
`cd /work/data/` at initialization of Docker container

### ISSUE THREAD

**Issue by wmkouw** [ADAH-EviDENce/NewsReader#25]
At initialization of Docker container, the following response is generated immediately:
```shell
bash: cd: /work/data: No such file or directory
```

Apparently, the container is tasked with changing directory to `/work/data` at initialization. But I don't know where this command is coming from; there is no .bashrc in the container.

**Comment by MartineDeVos** [comment]
Maybe it is the ENTRYPOINT of the Alpino Docker? I'll check that

**Comment by wmkouw** [comment]
Yes, it is:
```
CMD ["/bin/bash", "--rcfile", "/init.sh"]
```
